/*
 * HR API
 * <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>
 *
 * The version of the OpenAPI document: 2
 * Contact: hrapi@iris.co.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AbsenceReasonModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AbsenceReasonQueryModel
 */
public class AbsenceReasonQueryModelTest {
    private final AbsenceReasonQueryModel model = new AbsenceReasonQueryModel();

    /**
     * Model tests for AbsenceReasonQueryModel
     */
    @Test
    public void testAbsenceReasonQueryModel() {
        // TODO: test AbsenceReasonQueryModel
    }

    /**
     * Test the property 'odataContext'
     */
    @Test
    public void odataContextTest() {
        // TODO: test odataContext
    }

    /**
     * Test the property 'odataCount'
     */
    @Test
    public void odataCountTest() {
        // TODO: test odataCount
    }

    /**
     * Test the property 'odataNextLink'
     */
    @Test
    public void odataNextLinkTest() {
        // TODO: test odataNextLink
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
