/*
 * HR API
 * <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>
 *
 * The version of the OpenAPI document: 2
 * Contact: hrapi@iris.co.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DayPart;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AbsenceDayModel
 */
public class AbsenceDayModelTest {
    private final AbsenceDayModel model = new AbsenceDayModel();

    /**
     * Model tests for AbsenceDayModel
     */
    @Test
    public void testAbsenceDayModel() {
        // TODO: test AbsenceDayModel
    }

    /**
     * Test the property 'absenceId'
     */
    @Test
    public void absenceIdTest() {
        // TODO: test absenceId
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'durationDays'
     */
    @Test
    public void durationDaysTest() {
        // TODO: test durationDays
    }

    /**
     * Test the property 'durationMinutes'
     */
    @Test
    public void durationMinutesTest() {
        // TODO: test durationMinutes
    }

    /**
     * Test the property 'dayPart'
     */
    @Test
    public void dayPartTest() {
        // TODO: test dayPart
    }

    /**
     * Test the property 'sourceSystemId'
     */
    @Test
    public void sourceSystemIdTest() {
        // TODO: test sourceSystemId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    public void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'lastModifiedOn'
     */
    @Test
    public void lastModifiedOnTest() {
        // TODO: test lastModifiedOn
    }

    /**
     * Test the property 'lastModifiedBy'
     */
    @Test
    public void lastModifiedByTest() {
        // TODO: test lastModifiedBy
    }

}
