/*
 * HR API
 * <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>
 *
 * The version of the OpenAPI document: 2
 * Contact: hrapi@iris.co.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BankAddress;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateBankDetailsCommand
 */
public class CreateBankDetailsCommandTest {
    private final CreateBankDetailsCommand model = new CreateBankDetailsCommand();

    /**
     * Model tests for CreateBankDetailsCommand
     */
    @Test
    public void testCreateBankDetailsCommand() {
        // TODO: test CreateBankDetailsCommand
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'bankName'
     */
    @Test
    public void bankNameTest() {
        // TODO: test bankName
    }

    /**
     * Test the property 'bankAddress'
     */
    @Test
    public void bankAddressTest() {
        // TODO: test bankAddress
    }

    /**
     * Test the property 'accountName'
     */
    @Test
    public void accountNameTest() {
        // TODO: test accountName
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'sortCode'
     */
    @Test
    public void sortCodeTest() {
        // TODO: test sortCode
    }

    /**
     * Test the property 'rollNumber'
     */
    @Test
    public void rollNumberTest() {
        // TODO: test rollNumber
    }

}
