/*
 * HR API
 * <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>
 *
 * The version of the OpenAPI document: 2
 * Contact: hrapi@iris.co.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeAbsenceReasonModel
 */
public class EmployeeAbsenceReasonModelTest {
    private final EmployeeAbsenceReasonModel model = new EmployeeAbsenceReasonModel();

    /**
     * Model tests for EmployeeAbsenceReasonModel
     */
    @Test
    public void testEmployeeAbsenceReasonModel() {
        // TODO: test EmployeeAbsenceReasonModel
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'absenceReasonId'
     */
    @Test
    public void absenceReasonIdTest() {
        // TODO: test absenceReasonId
    }

    /**
     * Test the property 'showInDays'
     */
    @Test
    public void showInDaysTest() {
        // TODO: test showInDays
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    public void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'lastModifiedOn'
     */
    @Test
    public void lastModifiedOnTest() {
        // TODO: test lastModifiedOn
    }

    /**
     * Test the property 'lastModifiedBy'
     */
    @Test
    public void lastModifiedByTest() {
        // TODO: test lastModifiedBy
    }

}
