/*
 * HR API
 * <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>
 *
 * The version of the OpenAPI document: 2
 * Contact: hrapi@iris.co.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EntitlementModel
 */
public class EntitlementModelTest {
    private final EntitlementModel model = new EntitlementModel();

    /**
     * Model tests for EntitlementModel
     */
    @Test
    public void testEntitlementModel() {
        // TODO: test EntitlementModel
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'absenceReasonId'
     */
    @Test
    public void absenceReasonIdTest() {
        // TODO: test absenceReasonId
    }

    /**
     * Test the property 'entitlementYearName'
     */
    @Test
    public void entitlementYearNameTest() {
        // TODO: test entitlementYearName
    }

    /**
     * Test the property 'open'
     */
    @Test
    public void openTest() {
        // TODO: test open
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'narrative'
     */
    @Test
    public void narrativeTest() {
        // TODO: test narrative
    }

    /**
     * Test the property 'baseDays'
     */
    @Test
    public void baseDaysTest() {
        // TODO: test baseDays
    }

    /**
     * Test the property 'baseMinutes'
     */
    @Test
    public void baseMinutesTest() {
        // TODO: test baseMinutes
    }

    /**
     * Test the property 'carryDays'
     */
    @Test
    public void carryDaysTest() {
        // TODO: test carryDays
    }

    /**
     * Test the property 'carryMinutes'
     */
    @Test
    public void carryMinutesTest() {
        // TODO: test carryMinutes
    }

    /**
     * Test the property 'carryUseByDate'
     */
    @Test
    public void carryUseByDateTest() {
        // TODO: test carryUseByDate
    }

    /**
     * Test the property 'carryLostDays'
     */
    @Test
    public void carryLostDaysTest() {
        // TODO: test carryLostDays
    }

    /**
     * Test the property 'carryLostMinutes'
     */
    @Test
    public void carryLostMinutesTest() {
        // TODO: test carryLostMinutes
    }

    /**
     * Test the property 'manualAdjustmentDays'
     */
    @Test
    public void manualAdjustmentDaysTest() {
        // TODO: test manualAdjustmentDays
    }

    /**
     * Test the property 'manualAdjustmentMinutes'
     */
    @Test
    public void manualAdjustmentMinutesTest() {
        // TODO: test manualAdjustmentMinutes
    }

    /**
     * Test the property 'serviceLengthAdjustmentDays'
     */
    @Test
    public void serviceLengthAdjustmentDaysTest() {
        // TODO: test serviceLengthAdjustmentDays
    }

    /**
     * Test the property 'serviceLengthAdjustmentMinutes'
     */
    @Test
    public void serviceLengthAdjustmentMinutesTest() {
        // TODO: test serviceLengthAdjustmentMinutes
    }

    /**
     * Test the property 'newStarterAdjustmentDays'
     */
    @Test
    public void newStarterAdjustmentDaysTest() {
        // TODO: test newStarterAdjustmentDays
    }

    /**
     * Test the property 'newStarterAdjustmentMinutes'
     */
    @Test
    public void newStarterAdjustmentMinutesTest() {
        // TODO: test newStarterAdjustmentMinutes
    }

    /**
     * Test the property 'leaverAdjusmentDays'
     */
    @Test
    public void leaverAdjusmentDaysTest() {
        // TODO: test leaverAdjusmentDays
    }

    /**
     * Test the property 'leaverAdjusmentMinutes'
     */
    @Test
    public void leaverAdjusmentMinutesTest() {
        // TODO: test leaverAdjusmentMinutes
    }

    /**
     * Test the property 'leaverAdjustmentDays'
     */
    @Test
    public void leaverAdjustmentDaysTest() {
        // TODO: test leaverAdjustmentDays
    }

    /**
     * Test the property 'leaverAdjustmentMinutes'
     */
    @Test
    public void leaverAdjustmentMinutesTest() {
        // TODO: test leaverAdjustmentMinutes
    }

    /**
     * Test the property 'partTimeAdjustmentDays'
     */
    @Test
    public void partTimeAdjustmentDaysTest() {
        // TODO: test partTimeAdjustmentDays
    }

    /**
     * Test the property 'partTimeAdjustmentMinutes'
     */
    @Test
    public void partTimeAdjustmentMinutesTest() {
        // TODO: test partTimeAdjustmentMinutes
    }

    /**
     * Test the property 'bankHolidayAdjustmentDays'
     */
    @Test
    public void bankHolidayAdjustmentDaysTest() {
        // TODO: test bankHolidayAdjustmentDays
    }

    /**
     * Test the property 'bankHolidayAdjustmentMinutes'
     */
    @Test
    public void bankHolidayAdjustmentMinutesTest() {
        // TODO: test bankHolidayAdjustmentMinutes
    }

    /**
     * Test the property 'buySellDays'
     */
    @Test
    public void buySellDaysTest() {
        // TODO: test buySellDays
    }

    /**
     * Test the property 'buySellMinutes'
     */
    @Test
    public void buySellMinutesTest() {
        // TODO: test buySellMinutes
    }

    /**
     * Test the property 'totalEntitlementDays'
     */
    @Test
    public void totalEntitlementDaysTest() {
        // TODO: test totalEntitlementDays
    }

    /**
     * Test the property 'totalEntitlementMinutes'
     */
    @Test
    public void totalEntitlementMinutesTest() {
        // TODO: test totalEntitlementMinutes
    }

    /**
     * Test the property 'sourceSystemId'
     */
    @Test
    public void sourceSystemIdTest() {
        // TODO: test sourceSystemId
    }

    /**
     * Test the property 'sourceSystemCreatedOn'
     */
    @Test
    public void sourceSystemCreatedOnTest() {
        // TODO: test sourceSystemCreatedOn
    }

    /**
     * Test the property 'sourceSystemLastModifiedOn'
     */
    @Test
    public void sourceSystemLastModifiedOnTest() {
        // TODO: test sourceSystemLastModifiedOn
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    public void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'lastModifiedOn'
     */
    @Test
    public void lastModifiedOnTest() {
        // TODO: test lastModifiedOn
    }

    /**
     * Test the property 'lastModifiedBy'
     */
    @Test
    public void lastModifiedByTest() {
        // TODO: test lastModifiedBy
    }

}
