/*
 * HR API
 * <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>
 *
 * The version of the OpenAPI document: 2
 * Contact: hrapi@iris.co.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateJobCommand
 */
public class UpdateJobCommandTest {
    private final UpdateJobCommand model = new UpdateJobCommand();

    /**
     * Model tests for UpdateJobCommand
     */
    @Test
    public void testUpdateJobCommand() {
        // TODO: test UpdateJobCommand
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'classification'
     */
    @Test
    public void classificationTest() {
        // TODO: test classification
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'workingCalendar'
     */
    @Test
    public void workingCalendarTest() {
        // TODO: test workingCalendar
    }

    /**
     * Test the property 'lineManagerId'
     */
    @Test
    public void lineManagerIdTest() {
        // TODO: test lineManagerId
    }

    /**
     * Test the property 'hierarchyNodeId'
     */
    @Test
    public void hierarchyNodeIdTest() {
        // TODO: test hierarchyNodeId
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'salary'
     */
    @Test
    public void salaryTest() {
        // TODO: test salary
    }

    /**
     * Test the property 'contract'
     */
    @Test
    public void contractTest() {
        // TODO: test contract
    }

    /**
     * Test the property 'payFrequency'
     */
    @Test
    public void payFrequencyTest() {
        // TODO: test payFrequency
    }

    /**
     * Test the property 'payBasis'
     */
    @Test
    public void payBasisTest() {
        // TODO: test payBasis
    }

    /**
     * Test the property 'fullTimeEquivalent'
     */
    @Test
    public void fullTimeEquivalentTest() {
        // TODO: test fullTimeEquivalent
    }

    /**
     * Test the property 'changeReason'
     */
    @Test
    public void changeReasonTest() {
        // TODO: test changeReason
    }

    /**
     * Test the property 'nextIncrementDate'
     */
    @Test
    public void nextIncrementDateTest() {
        // TODO: test nextIncrementDate
    }

    /**
     * Test the property 'timesheetLocation'
     */
    @Test
    public void timesheetLocationTest() {
        // TODO: test timesheetLocation
    }

    /**
     * Test the property 'timesheetLunchDuration'
     */
    @Test
    public void timesheetLunchDurationTest() {
        // TODO: test timesheetLunchDuration
    }

    /**
     * Test the property 'expenseSubmissionFrequency'
     */
    @Test
    public void expenseSubmissionFrequencyTest() {
        // TODO: test expenseSubmissionFrequency
    }

    /**
     * Test the property 'costCentre'
     */
    @Test
    public void costCentreTest() {
        // TODO: test costCentre
    }

    /**
     * Test the property 'jobFamily'
     */
    @Test
    public void jobFamilyTest() {
        // TODO: test jobFamily
    }

    /**
     * Test the property 'apprenticeUnder25'
     */
    @Test
    public void apprenticeUnder25Test() {
        // TODO: test apprenticeUnder25
    }

    /**
     * Test the property 'apprenticeshipEndDate'
     */
    @Test
    public void apprenticeshipEndDateTest() {
        // TODO: test apprenticeshipEndDate
    }

    /**
     * Test the property 'contractEndDate'
     */
    @Test
    public void contractEndDateTest() {
        // TODO: test contractEndDate
    }

    /**
     * Test the property 'normalHours'
     */
    @Test
    public void normalHoursTest() {
        // TODO: test normalHours
    }

    /**
     * Test the property 'realTimeInformationIrregularFrequency'
     */
    @Test
    public void realTimeInformationIrregularFrequencyTest() {
        // TODO: test realTimeInformationIrregularFrequency
    }

    /**
     * Test the property 'noticePeriod'
     */
    @Test
    public void noticePeriodTest() {
        // TODO: test noticePeriod
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
