/*
 * HR API
 * <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>
 *
 * The version of the OpenAPI document: 2
 * Contact: hrapi@iris.co.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AbsenceDayModel;
import com.konfigthis.client.model.AbsenceDayQueryModel;
import com.konfigthis.client.model.CreateAbsenceDayCommand;
import com.konfigthis.client.model.DayPart;
import java.time.OffsetDateTime;
import com.konfigthis.client.model.UpdateAbsenceDayCommand;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AbsenceDaysApi
 */
@Disabled
public class AbsenceDaysApiTest {

    private static AbsenceDaysApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AbsenceDaysApi(apiClient);
    }

    /**
     * Creates an Absence Day.
     *
     * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) &lt;b&gt;This API request method is currently in beta testing.&lt;/b&gt; To gain access to use this method, please contact &lt;a href&#x3D;&#39;mailto:hrapi@iris.co.uk&#39;&gt;hrapi@iris.co.uk.&lt;/a&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAbsenceDayTest() throws ApiException {
        String absenceId = null;
        String employeeId = null;
        OffsetDateTime date = null;
        Double durationDays = null;
        Integer durationMinutes = null;
        DayPart dayPart = null;
        String response = api.createAbsenceDay()
                .absenceId(absenceId)
                .employeeId(employeeId)
                .date(date)
                .durationDays(durationDays)
                .durationMinutes(durationMinutes)
                .dayPart(dayPart)
                .execute();
        // TODO: test validations
    }

    /**
     * Deletes an Absence Day.
     *
     * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) &lt;b&gt;This API request method is currently in beta testing.&lt;/b&gt; To gain access to use this method, please contact &lt;a href&#x3D;&#39;mailto:hrapi@iris.co.uk&#39;&gt;hrapi@iris.co.uk.&lt;/a&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteByIdTest() throws ApiException {
        String id = null;
        api.deleteById(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Gets a single Absence Day based on ID given.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        String id = null;
        AbsenceDayModel response = api.getById(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Gets a list of all Absence Days.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListTest() throws ApiException {
        Integer $top = null;
        Integer $skip = null;
        String $filter = null;
        List<String> $select = null;
        String $orderby = null;
        Boolean $count = null;
        AbsenceDayQueryModel response = api.getList()
                .$top($top)
                .$skip($skip)
                .$filter($filter)
                .$select($select)
                .$orderby($orderby)
                .$count($count)
                .execute();
        // TODO: test validations
    }

    /**
     * Updates an Absence Day.
     *
     * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) &lt;b&gt;This API request method is currently in beta testing.&lt;/b&gt; To gain access to use this method, please contact &lt;a href&#x3D;&#39;mailto:hrapi@iris.co.uk&#39;&gt;hrapi@iris.co.uk.&lt;/a&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAbsenceDayTest() throws ApiException {
        String id = null;
        OffsetDateTime date = null;
        Double durationDays = null;
        Integer durationMinutes = null;
        DayPart dayPart = null;
        String id = null;
        api.updateAbsenceDay(id)
                .date(date)
                .durationDays(durationDays)
                .durationMinutes(durationMinutes)
                .dayPart(dayPart)
                .id(id)
                .execute();
        // TODO: test validations
    }

}
