/*
 * HR API
 * <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>
 *
 * The version of the OpenAPI document: 2
 * Contact: hrapi@iris.co.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.HierarchyNodeModel;
import com.konfigthis.client.model.HierarchyNodeQueryModel;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HierarchyApi
 */
@Disabled
public class HierarchyApiTest {

    private static HierarchyApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new HierarchyApi(apiClient);
    }

    /**
     * Gets a list of Hierarchy Nodes.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListTest() throws ApiException {
        Integer $top = null;
        Integer $skip = null;
        String $filter = null;
        List<String> $select = null;
        String $orderby = null;
        Boolean $count = null;
        HierarchyNodeQueryModel response = api.getList()
                .$top($top)
                .$skip($skip)
                .$filter($filter)
                .$select($select)
                .$orderby($orderby)
                .$count($count)
                .execute();
        // TODO: test validations
    }

    /**
     * Gets a single Hierarchy Node by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNodeByIdTest() throws ApiException {
        String id = null;
        HierarchyNodeModel response = api.getNodeById(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Gets a Hierarchy Path by ID. The path is an array of nodes traversed from the root to the node specified.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPathByIdTest() throws ApiException {
        String id = null;
        HierarchyNodeModel response = api.getPathById(id)
                .execute();
        // TODO: test validations
    }

}
