/*
 * HR API
 * <a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>
 *
 * The version of the OpenAPI document: 2
 * Contact: hrapi@iris.co.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.BankAddress;
import com.konfigthis.client.model.BankDetailsModel;
import com.konfigthis.client.model.BankDetailsQueryModel;
import com.konfigthis.client.model.CreateBankDetailsCommand;
import com.konfigthis.client.model.UpdateBankDetailsCommand;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class BankDetailsApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public BankDetailsApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public BankDetailsApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call createBankDetailCall(CreateBankDetailsCommand createBankDetailsCommand, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createBankDetailsCommand;

        // create path and map variables
        String localVarPath = "/bankdetails";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json;odata.metadata=minimal;odata.streaming=true; version=1",
            "application/json;odata.metadata=minimal;odata.streaming=false; version=1",
            "application/json;odata.metadata=minimal; version=1",
            "application/json;odata.metadata=full;odata.streaming=true; version=1",
            "application/json;odata.metadata=full;odata.streaming=false; version=1",
            "application/json;odata.metadata=full; version=1",
            "application/json;odata.metadata=none;odata.streaming=true; version=1",
            "application/json;odata.metadata=none;odata.streaming=false; version=1",
            "application/json;odata.metadata=none; version=1",
            "application/json;odata.streaming=true; version=1",
            "application/json;odata.streaming=false; version=1",
            "application/json; version=1",
            "application/xml; version=1",
            "application/prs.odatatestxx-odata; version=1",
            "text/plain; version=1",
            "text/json; version=1"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json;odata.metadata=minimal;odata.streaming=true; version=1",
            "application/json;odata.metadata=minimal;odata.streaming=false; version=1",
            "application/json;odata.metadata=minimal; version=1",
            "application/json;odata.metadata=full;odata.streaming=true; version=1",
            "application/json;odata.metadata=full;odata.streaming=false; version=1",
            "application/json;odata.metadata=full; version=1",
            "application/json;odata.metadata=none;odata.streaming=true; version=1",
            "application/json;odata.metadata=none;odata.streaming=false; version=1",
            "application/json;odata.metadata=none; version=1",
            "application/json;odata.streaming=true; version=1",
            "application/json;odata.streaming=false; version=1",
            "application/json; version=1",
            "application/xml; version=1",
            "application/prs.odatatestxx-odata; version=1",
            "text/json; version=1",
            "application/*+json; version=1"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createBankDetailValidateBeforeCall(CreateBankDetailsCommand createBankDetailsCommand, final ApiCallback _callback) throws ApiException {
        return createBankDetailCall(createBankDetailsCommand, _callback);

    }


    private ApiResponse<String> createBankDetailWithHttpInfo(CreateBankDetailsCommand createBankDetailsCommand) throws ApiException {
        okhttp3.Call localVarCall = createBankDetailValidateBeforeCall(createBankDetailsCommand, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call createBankDetailAsync(CreateBankDetailsCommand createBankDetailsCommand, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = createBankDetailValidateBeforeCall(createBankDetailsCommand, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class CreateBankDetailRequestBuilder {
        private String employeeId;
        private String bankName;
        private BankAddress bankAddress;
        private String accountName;
        private String accountNumber;
        private String sortCode;
        private String rollNumber;

        private CreateBankDetailRequestBuilder() {
        }

        /**
         * Set employeeId
         * @param employeeId The ID of the HR Employee. &lt;br /&gt;  Must exist in the Employee Service. (optional)
         * @return CreateBankDetailRequestBuilder
         */
        public CreateBankDetailRequestBuilder employeeId(String employeeId) {
            this.employeeId = employeeId;
            return this;
        }
        
        /**
         * Set bankName
         * @param bankName Bank Name. &lt;br /&gt;  Cascade Source: [EmployeeBank].[BankName] (optional)
         * @return CreateBankDetailRequestBuilder
         */
        public CreateBankDetailRequestBuilder bankName(String bankName) {
            this.bankName = bankName;
            return this;
        }
        
        /**
         * Set bankAddress
         * @param bankAddress  (optional)
         * @return CreateBankDetailRequestBuilder
         */
        public CreateBankDetailRequestBuilder bankAddress(BankAddress bankAddress) {
            this.bankAddress = bankAddress;
            return this;
        }
        
        /**
         * Set accountName
         * @param accountName Account Name. &lt;br /&gt;  Cascade Source: [EmployeeBank].[AccountName] (optional)
         * @return CreateBankDetailRequestBuilder
         */
        public CreateBankDetailRequestBuilder accountName(String accountName) {
            this.accountName = accountName;
            return this;
        }
        
        /**
         * Set accountNumber
         * @param accountNumber Account Number. &lt;br /&gt;  Cascade Source: [EmployeeBank].[AccountNumber] (optional)
         * @return CreateBankDetailRequestBuilder
         */
        public CreateBankDetailRequestBuilder accountNumber(String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }
        
        /**
         * Set sortCode
         * @param sortCode Sort Code. &lt;br /&gt;  Cascade Source: [EmployeeBank].[SortCode] (optional)
         * @return CreateBankDetailRequestBuilder
         */
        public CreateBankDetailRequestBuilder sortCode(String sortCode) {
            this.sortCode = sortCode;
            return this;
        }
        
        /**
         * Set rollNumber
         * @param rollNumber Roll Number. &lt;br /&gt;  Cascade Source: [EmployeeBank].[RollNumber] (optional)
         * @return CreateBankDetailRequestBuilder
         */
        public CreateBankDetailRequestBuilder rollNumber(String rollNumber) {
            this.rollNumber = rollNumber;
            return this;
        }
        
        /**
         * Build call for createBankDetail
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            CreateBankDetailsCommand createBankDetailsCommand = buildBodyParams();
            return createBankDetailCall(createBankDetailsCommand, _callback);
        }

        private CreateBankDetailsCommand buildBodyParams() {
            CreateBankDetailsCommand createBankDetailsCommand = new CreateBankDetailsCommand();
            createBankDetailsCommand.employeeId(this.employeeId);
            createBankDetailsCommand.bankName(this.bankName);
            createBankDetailsCommand.bankAddress(this.bankAddress);
            createBankDetailsCommand.accountName(this.accountName);
            createBankDetailsCommand.accountNumber(this.accountNumber);
            createBankDetailsCommand.sortCode(this.sortCode);
            createBankDetailsCommand.rollNumber(this.rollNumber);
            return createBankDetailsCommand;
        }

        /**
         * Execute createBankDetail request
         * @return String
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public String execute() throws ApiException {
            CreateBankDetailsCommand createBankDetailsCommand = buildBodyParams();
            ApiResponse<String> localVarResp = createBankDetailWithHttpInfo(createBankDetailsCommand);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute createBankDetail request with HTTP info returned
         * @return ApiResponse&lt;String&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<String> executeWithHttpInfo() throws ApiException {
            CreateBankDetailsCommand createBankDetailsCommand = buildBodyParams();
            return createBankDetailWithHttpInfo(createBankDetailsCommand);
        }

        /**
         * Execute createBankDetail request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<String> _callback) throws ApiException {
            CreateBankDetailsCommand createBankDetailsCommand = buildBodyParams();
            return createBankDetailAsync(createBankDetailsCommand, _callback);
        }
    }

    /**
     * Creates a Bank Details.
     * 
     * @return CreateBankDetailRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public CreateBankDetailRequestBuilder createBankDetail() throws IllegalArgumentException {
        return new CreateBankDetailRequestBuilder();
    }
    private okhttp3.Call getByIdCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/bankdetails/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json;odata.metadata=minimal;odata.streaming=true; version=1",
            "application/json;odata.metadata=minimal;odata.streaming=false; version=1",
            "application/json;odata.metadata=minimal; version=1",
            "application/json;odata.metadata=full;odata.streaming=true; version=1",
            "application/json;odata.metadata=full;odata.streaming=false; version=1",
            "application/json;odata.metadata=full; version=1",
            "application/json;odata.metadata=none;odata.streaming=true; version=1",
            "application/json;odata.metadata=none;odata.streaming=false; version=1",
            "application/json;odata.metadata=none; version=1",
            "application/json;odata.streaming=true; version=1",
            "application/json;odata.streaming=false; version=1",
            "application/json; version=1",
            "application/xml; version=1",
            "application/prs.odatatestxx-odata; version=1",
            "text/plain; version=1",
            "text/json; version=1"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getByIdValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getById(Async)");
        }

        return getByIdCall(id, _callback);

    }


    private ApiResponse<BankDetailsModel> getByIdWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<BankDetailsModel>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getByIdAsync(String id, final ApiCallback<BankDetailsModel> _callback) throws ApiException {

        okhttp3.Call localVarCall = getByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<BankDetailsModel>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetByIdRequestBuilder {
        private final String id;

        private GetByIdRequestBuilder(String id) {
            this.id = id;
        }

        /**
         * Build call for getById
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getByIdCall(id, _callback);
        }


        /**
         * Execute getById request
         * @return BankDetailsModel
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public BankDetailsModel execute() throws ApiException {
            ApiResponse<BankDetailsModel> localVarResp = getByIdWithHttpInfo(id);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getById request with HTTP info returned
         * @return ApiResponse&lt;BankDetailsModel&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<BankDetailsModel> executeWithHttpInfo() throws ApiException {
            return getByIdWithHttpInfo(id);
        }

        /**
         * Execute getById request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<BankDetailsModel> _callback) throws ApiException {
            return getByIdAsync(id, _callback);
        }
    }

    /**
     * Gets a single Bank Details by an ID.
     * 
     * @param id Bank Details ID. (required)
     * @return GetByIdRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public GetByIdRequestBuilder getById(String id) throws IllegalArgumentException {
        if (id == null) throw new IllegalArgumentException("\"id\" is required but got null");
            

        return new GetByIdRequestBuilder(id);
    }
    private okhttp3.Call getListCall(Integer $top, Integer $skip, String $filter, List<String> $select, String $orderby, Boolean $count, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/bankdetails";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if ($top != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("$top", $top));
        }

        if ($skip != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("$skip", $skip));
        }

        if ($filter != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("$filter", $filter));
        }

        if ($select != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("csv", "$select", $select));
        }

        if ($orderby != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("$orderby", $orderby));
        }

        if ($count != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("$count", $count));
        }

        final String[] localVarAccepts = {
            "application/json;odata.metadata=minimal;odata.streaming=true; version=1",
            "application/json;odata.metadata=minimal;odata.streaming=false; version=1",
            "application/json;odata.metadata=minimal; version=1",
            "application/json;odata.metadata=full;odata.streaming=true; version=1",
            "application/json;odata.metadata=full;odata.streaming=false; version=1",
            "application/json;odata.metadata=full; version=1",
            "application/json;odata.metadata=none;odata.streaming=true; version=1",
            "application/json;odata.metadata=none;odata.streaming=false; version=1",
            "application/json;odata.metadata=none; version=1",
            "application/json;odata.streaming=true; version=1",
            "application/json;odata.streaming=false; version=1",
            "application/json; version=1",
            "application/xml; version=1",
            "application/prs.odatatestxx-odata; version=1",
            "text/plain; version=1",
            "text/json; version=1"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getListValidateBeforeCall(Integer $top, Integer $skip, String $filter, List<String> $select, String $orderby, Boolean $count, final ApiCallback _callback) throws ApiException {
        return getListCall($top, $skip, $filter, $select, $orderby, $count, _callback);

    }


    private ApiResponse<BankDetailsQueryModel> getListWithHttpInfo(Integer $top, Integer $skip, String $filter, List<String> $select, String $orderby, Boolean $count) throws ApiException {
        okhttp3.Call localVarCall = getListValidateBeforeCall($top, $skip, $filter, $select, $orderby, $count, null);
        Type localVarReturnType = new TypeToken<BankDetailsQueryModel>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getListAsync(Integer $top, Integer $skip, String $filter, List<String> $select, String $orderby, Boolean $count, final ApiCallback<BankDetailsQueryModel> _callback) throws ApiException {

        okhttp3.Call localVarCall = getListValidateBeforeCall($top, $skip, $filter, $select, $orderby, $count, _callback);
        Type localVarReturnType = new TypeToken<BankDetailsQueryModel>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetListRequestBuilder {
        private Integer $top;
        private Integer $skip;
        private String $filter;
        private List<String> $select;
        private String $orderby;
        private Boolean $count;

        private GetListRequestBuilder() {
        }

        /**
         * Set $top
         * @param $top Show only the first n items, maximum of 250, see [Paging - Top](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop) (optional)
         * @return GetListRequestBuilder
         */
        public GetListRequestBuilder $top(Integer $top) {
            this.$top = $top;
            return this;
        }
        
        /**
         * Set $skip
         * @param $skip Skip the first n items, see [Paging - Skip](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip) (optional)
         * @return GetListRequestBuilder
         */
        public GetListRequestBuilder $skip(Integer $skip) {
            this.$skip = $skip;
            return this;
        }
        
        /**
         * Set $filter
         * @param $filter Filter items by property values, see [Filtering](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter) (optional)
         * @return GetListRequestBuilder
         */
        public GetListRequestBuilder $filter(String $filter) {
            this.$filter = $filter;
            return this;
        }
        
        /**
         * Set $select
         * @param $select Select properties to be returned, see [Select](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
         * @return GetListRequestBuilder
         */
        public GetListRequestBuilder $select(List<String> $select) {
            this.$select = $select;
            return this;
        }
        
        /**
         * Set $orderby
         * @param $orderby Order items by property values, see [Sorting](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby) (optional)
         * @return GetListRequestBuilder
         */
        public GetListRequestBuilder $orderby(String $orderby) {
            this.$orderby = $orderby;
            return this;
        }
        
        /**
         * Set $count
         * @param $count Include count of items, see [Count](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount) (optional)
         * @return GetListRequestBuilder
         */
        public GetListRequestBuilder $count(Boolean $count) {
            this.$count = $count;
            return this;
        }
        
        /**
         * Build call for getList
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getListCall($top, $skip, $filter, $select, $orderby, $count, _callback);
        }


        /**
         * Execute getList request
         * @return BankDetailsQueryModel
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public BankDetailsQueryModel execute() throws ApiException {
            ApiResponse<BankDetailsQueryModel> localVarResp = getListWithHttpInfo($top, $skip, $filter, $select, $orderby, $count);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getList request with HTTP info returned
         * @return ApiResponse&lt;BankDetailsQueryModel&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<BankDetailsQueryModel> executeWithHttpInfo() throws ApiException {
            return getListWithHttpInfo($top, $skip, $filter, $select, $orderby, $count);
        }

        /**
         * Execute getList request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<BankDetailsQueryModel> _callback) throws ApiException {
            return getListAsync($top, $skip, $filter, $select, $orderby, $count, _callback);
        }
    }

    /**
     * Gets a list of Bank Details.
     * 
     * @return GetListRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public GetListRequestBuilder getList() throws IllegalArgumentException {
        return new GetListRequestBuilder();
    }
    private okhttp3.Call updateBankDetailCall(String id, UpdateBankDetailsCommand updateBankDetailsCommand, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateBankDetailsCommand;

        // create path and map variables
        String localVarPath = "/bankdetails/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json;odata.metadata=minimal;odata.streaming=true; version=1",
            "application/json;odata.metadata=minimal;odata.streaming=false; version=1",
            "application/json;odata.metadata=minimal; version=1",
            "application/json;odata.metadata=full;odata.streaming=true; version=1",
            "application/json;odata.metadata=full;odata.streaming=false; version=1",
            "application/json;odata.metadata=full; version=1",
            "application/json;odata.metadata=none;odata.streaming=true; version=1",
            "application/json;odata.metadata=none;odata.streaming=false; version=1",
            "application/json;odata.metadata=none; version=1",
            "application/json;odata.streaming=true; version=1",
            "application/json;odata.streaming=false; version=1",
            "application/json; version=1",
            "application/xml; version=1",
            "application/prs.odatatestxx-odata; version=1",
            "text/plain; version=1",
            "text/json; version=1"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json;odata.metadata=minimal;odata.streaming=true; version=1",
            "application/json;odata.metadata=minimal;odata.streaming=false; version=1",
            "application/json;odata.metadata=minimal; version=1",
            "application/json;odata.metadata=full;odata.streaming=true; version=1",
            "application/json;odata.metadata=full;odata.streaming=false; version=1",
            "application/json;odata.metadata=full; version=1",
            "application/json;odata.metadata=none;odata.streaming=true; version=1",
            "application/json;odata.metadata=none;odata.streaming=false; version=1",
            "application/json;odata.metadata=none; version=1",
            "application/json;odata.streaming=true; version=1",
            "application/json;odata.streaming=false; version=1",
            "application/json; version=1",
            "application/xml; version=1",
            "application/prs.odatatestxx-odata; version=1",
            "text/json; version=1",
            "application/*+json; version=1"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateBankDetailValidateBeforeCall(String id, UpdateBankDetailsCommand updateBankDetailsCommand, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateBankDetail(Async)");
        }

        return updateBankDetailCall(id, updateBankDetailsCommand, _callback);

    }


    private ApiResponse<Void> updateBankDetailWithHttpInfo(String id, UpdateBankDetailsCommand updateBankDetailsCommand) throws ApiException {
        okhttp3.Call localVarCall = updateBankDetailValidateBeforeCall(id, updateBankDetailsCommand, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call updateBankDetailAsync(String id, UpdateBankDetailsCommand updateBankDetailsCommand, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateBankDetailValidateBeforeCall(id, updateBankDetailsCommand, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class UpdateBankDetailRequestBuilder {
        private final String id;
        private String bankName;
        private BankAddress bankAddress;
        private String accountName;
        private String accountNumber;
        private String sortCode;
        private String rollNumber;
        private String id;

        private UpdateBankDetailRequestBuilder(String id) {
            this.id = id;
        }

        /**
         * Set bankName
         * @param bankName Bank Name. &lt;br /&gt;  Cascade Source: [EmployeeBank].[BankName] (optional)
         * @return UpdateBankDetailRequestBuilder
         */
        public UpdateBankDetailRequestBuilder bankName(String bankName) {
            this.bankName = bankName;
            return this;
        }
        
        /**
         * Set bankAddress
         * @param bankAddress  (optional)
         * @return UpdateBankDetailRequestBuilder
         */
        public UpdateBankDetailRequestBuilder bankAddress(BankAddress bankAddress) {
            this.bankAddress = bankAddress;
            return this;
        }
        
        /**
         * Set accountName
         * @param accountName Account Name. &lt;br /&gt;  Cascade Source: [EmployeeBank].[AccountName] (optional)
         * @return UpdateBankDetailRequestBuilder
         */
        public UpdateBankDetailRequestBuilder accountName(String accountName) {
            this.accountName = accountName;
            return this;
        }
        
        /**
         * Set accountNumber
         * @param accountNumber Account Number. &lt;br /&gt;  Cascade Source: [EmployeeBank].[AccountNumber] (optional)
         * @return UpdateBankDetailRequestBuilder
         */
        public UpdateBankDetailRequestBuilder accountNumber(String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }
        
        /**
         * Set sortCode
         * @param sortCode Sort Code. &lt;br /&gt;  Cascade Source: [EmployeeBank].[SortCode] (optional)
         * @return UpdateBankDetailRequestBuilder
         */
        public UpdateBankDetailRequestBuilder sortCode(String sortCode) {
            this.sortCode = sortCode;
            return this;
        }
        
        /**
         * Set rollNumber
         * @param rollNumber Roll Number. &lt;br /&gt;  Cascade Source: [EmployeeBank].[RollNumber] (optional)
         * @return UpdateBankDetailRequestBuilder
         */
        public UpdateBankDetailRequestBuilder rollNumber(String rollNumber) {
            this.rollNumber = rollNumber;
            return this;
        }
        
        /**
         * Set id
         * @param id The ID of Bank Details to update. &lt;br /&gt;  Must exist in Bank Details Service. (optional)
         * @return UpdateBankDetailRequestBuilder
         */
        public UpdateBankDetailRequestBuilder id(String id) {
            this.id = id;
            return this;
        }
        
        /**
         * Build call for updateBankDetail
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            UpdateBankDetailsCommand updateBankDetailsCommand = buildBodyParams();
            return updateBankDetailCall(id, updateBankDetailsCommand, _callback);
        }

        private UpdateBankDetailsCommand buildBodyParams() {
            UpdateBankDetailsCommand updateBankDetailsCommand = new UpdateBankDetailsCommand();
            updateBankDetailsCommand.bankName(this.bankName);
            updateBankDetailsCommand.bankAddress(this.bankAddress);
            updateBankDetailsCommand.accountName(this.accountName);
            updateBankDetailsCommand.accountNumber(this.accountNumber);
            updateBankDetailsCommand.sortCode(this.sortCode);
            updateBankDetailsCommand.rollNumber(this.rollNumber);
            updateBankDetailsCommand.id(this.id);
            return updateBankDetailsCommand;
        }

        /**
         * Execute updateBankDetail request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            UpdateBankDetailsCommand updateBankDetailsCommand = buildBodyParams();
            updateBankDetailWithHttpInfo(id, updateBankDetailsCommand);
        }

        /**
         * Execute updateBankDetail request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            UpdateBankDetailsCommand updateBankDetailsCommand = buildBodyParams();
            return updateBankDetailWithHttpInfo(id, updateBankDetailsCommand);
        }

        /**
         * Execute updateBankDetail request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            UpdateBankDetailsCommand updateBankDetailsCommand = buildBodyParams();
            return updateBankDetailAsync(id, updateBankDetailsCommand, _callback);
        }
    }

    /**
     * Updates Bank Details.
     * 
     * @param id The ID of Bank Details to update. (required)
     * @return UpdateBankDetailRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Success </td><td>  -  </td></tr>
     </table>
     */
    public UpdateBankDetailRequestBuilder updateBankDetail(String id) throws IllegalArgumentException {
        if (id == null) throw new IllegalArgumentException("\"id\" is required but got null");
            

        return new UpdateBankDetailRequestBuilder(id);
    }
}
